const KEY="baccaratxr_v34_real";const MSG={clear:"⚠ Clear Current Shoe?\n\nAll round history and active numbers will be reset.",win:"💰 CASHED IN!\n\nNumber {X} finally showed up!\nHit at Step {S}.\n\nProfit locked: ₹{P}\n\nOne soldier down.\nMoving to the next target 🎯",cap:"🚧 CAP HIT, BOSS!\n\nThis number climbed all the way to the roof.\nWe’re shutting it down before it gets too expensive.\n\nNumber {X} is now excluded.\nNo more chasing. Cool heads only 😎",target:"🎉 BOOM! TARGET SMASHED!\n\nYou didn’t gamble…\nYou executed the plan.\n\nProfit locked. Discipline level: PRO.\n\nClose the shoe, take the win,\nand let the casino breathe for a moment 😎"};
const blank=n=>({num:n,status:'inactive',misses:0,losses:0,closedProfit:0,capHit:false});
const side=()=>{const o={};for(let i=1;i<=9;i++)o[i]=blank(i);return o;};
const def={settings:{startingBankroll:30000,targetAmount:5000,minBet:100,maxBet:3000,multiple:100,profitTarget:500,safetyReserve:20000},bankroll:30000,pending:{player:null,banker:null},rounds:[],lastShoeSummary:null,player:side(),banker:side(),ladder:[],alerts:[]};
let s;const $=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v)),money=v=>'₹'+Number(v||0).toFixed(0),fmt=v=>v>=1000?((v/1000).toFixed(1).replace('.0','')+'k'):String(v),msg=(t,m)=>Object.keys(m).reduce((a,k)=>a.replaceAll('{'+k+'}',m[k]),t);
function load(){const raw=localStorage.getItem(KEY);s=raw?JSON.parse(raw):clone(def);if(!s.ladder.length)buildLadder();}
function save(){localStorage.setItem(KEY,JSON.stringify(s));}
function buildLadder(){let prior=0;s.ladder=[];for(let i=1;i<=60;i++){let b=Math.ceil(Math.max(s.settings.minBet,(s.settings.profitTarget+prior)/8)/s.settings.multiple)*s.settings.multiple;if(b>s.settings.maxBet)break;s.ladder.push(b);prior+=b;}let extra=Math.ceil(Math.max(s.settings.minBet,(s.settings.profitTarget+prior)/8)/s.settings.multiple)*s.settings.multiple;s.ladder.push(Math.min(extra,s.settings.maxBet));}
function nextBet(t){return s.ladder[Math.min(t.misses,s.ladder.length-1)]||0}function active(which){return Object.values(s[which]).filter(x=>x.status==='active')}function targetReached(){return s.bankroll-s.settings.startingBankroll>=s.settings.targetAmount}
function queue(text,buttons){s.alerts.push({text,buttons});save();}function modal(text,buttons){$('modalText').innerText=text;const box=$('modalActions');box.innerHTML='';buttons.forEach(btn=>{const b=document.createElement('button');b.className='pill'+(btn.kind?' '+btn.kind:'');b.textContent=btn.label;b.onclick=()=>{$('modal').classList.add('hidden');btn.onClick&&btn.onClick();};box.appendChild(b);});$('modal').classList.remove('hidden');}function flush(){if(!s.alerts.length)return;const a=s.alerts.shift();save();modal(a.text,a.buttons||[{label:'OK'}]);}
function process(which,result){const side=s[which],list=active(which);let net=0,exp=list.reduce((a,t)=>a+nextBet(t),0);if(result===0||(result>=1&&result<=9&&side[result].status==='excluded')){list.forEach(t=>{let b=nextBet(t);net-=b;t.losses+=b;t.misses++;if(t.misses+1>s.ladder.length&&!t.capHit){t.capHit=true;t.status='excluded';queue(msg(MSG.cap,{X:t.num}),[{label:'OK BOSS',kind:' gold'}]);}});return{net,exp};}const target=side[result];if(target.status==='inactive'){list.forEach(t=>{let b=nextBet(t);net-=b;t.losses+=b;t.misses++;if(t.misses+1>s.ladder.length&&!t.capHit){t.capHit=true;t.status='excluded';queue(msg(MSG.cap,{X:t.num}),[{label:'OK BOSS',kind:' gold'}]);}});target.status='active';target.misses=0;target.losses=0;return{net,exp};}if(target.status==='active'){list.forEach(t=>{let b=nextBet(t);if(t.num===result){net+=8*b;const profit=(8*b)-t.losses;t.closedProfit=profit;t.status='excluded';queue(msg(MSG.win,{X:t.num,S:t.misses+1,P:profit}),[{label:'NICE!',kind:' gold'}]);}else{net-=b;t.losses+=b;t.misses++;if(t.misses+1>s.ladder.length&&!t.capHit){t.capHit=true;t.status='excluded';queue(msg(MSG.cap,{X:t.num}),[{label:'OK BOSS',kind:' gold'}]);}}});}return{net,exp};}
function commit(p,b){const pr=process('player',Number(p)),br=process('banker',Number(b));const total=pr.net+br.net;s.bankroll+=total;s.rounds.push({p:Number(p),b:Number(b),pNet:pr.net,bNet:br.net,total,bankroll:s.bankroll});s.pending={player:null,banker:null};save();render();if(targetReached())queue(MSG.target,[{label:'Close Shoe',kind:' gold',onClick:()=>clearShoe(false)},{label:'Keep Playing'}]);setTimeout(flush,20);}
function setPending(which,val){s.pending[which]=val;(which==='player'?$('pendingPlayer'):$('pendingBanker')).textContent=val;if(s.pending.player!==null&&s.pending.banker!==null)commit(s.pending.player,s.pending.banker)}
function clearSummary(){const delta=s.bankroll-s.settings.startingBankroll,abs=Math.abs(delta),safety=s.settings.safetyReserve,type=delta>=0?'profit':'loss',suggested=type==='profit'?s.settings.startingBankroll+safety:s.settings.startingBankroll+abs+safety;s.lastShoeSummary={type,base:s.settings.startingBankroll,delta:abs,safety,suggested};}
function clearShoe(withSummary=true){if(withSummary)clearSummary();s.bankroll=s.settings.startingBankroll;s.rounds=[];s.pending={player:null,banker:null};s.player=side();s.banker=side();save();render();}
function renderPlay(){ $('startText').textContent=s.settings.startingBankroll;$('bankrollText').textContent=s.bankroll;$('pendingPlayer').textContent=s.pending.player===null?'—':s.pending.player;$('pendingBanker').textContent=s.pending.banker===null?'—':s.pending.banker;$('roundCount').textContent=s.rounds.length;const p=active('player'),b=active('banker'),pExp=p.reduce((a,t)=>a+nextBet(t),0),bExp=b.reduce((a,t)=>a+nextBet(t),0);$('pActive').textContent=p.length;$('bActive').textContent=b.length;$('pNext').textContent=money(pExp);$('bNext').textContent=money(bExp);$('playerMicro').textContent=p.length?p.map(t=>`${t.num} S${t.misses+1} ${fmt(nextBet(t))}`).join('  '):'—';$('bankerMicro').textContent=b.length?b.map(t=>`${t.num} S${t.misses+1} ${fmt(nextBet(t))}`).join('  '):'—';$('pExposure').textContent=money(pExp);$('bExposure').textContent=money(bExp);$('tExposure').textContent=money(pExp+bExp);$('last5').textContent=s.rounds.length?s.rounds.slice(-5).map(r=>`P${r.p}-B${r.b}`).join(' '):'—';const risk=Math.min(100,((pExp+bExp)/Math.max(1,s.bankroll))*100);$('riskFill').style.width=Math.max(4,risk)+'%';$('riskFill').style.background=risk<10?'#2fd07a':risk<25?'#f0c450':'#ef5d66';$('riskText').textContent=risk<10?'LOW':risk<25?'MED':'HIGH';}
function renderBoard(){['player','banker'].forEach(which=>{const wrap=$(which+'Board');wrap.innerHTML='';for(let i=1;i<=9;i++){const t=s[which][i],d=document.createElement('div');d.className='tile '+(t.status==='active'?'active-t':t.capHit?'cap':t.status==='excluded'?'excluded':'inactive');d.innerHTML=`<div class="num">${i}</div><div class="state">${t.capHit?'CAP HIT':t.status.toUpperCase()}</div><div class="bet">${t.status==='active'?'S'+(t.misses+1)+' • '+money(nextBet(t)):t.closedProfit?('WIN '+money(t.closedProfit)):'LOCKED'}</div>`;wrap.appendChild(d);}})}
function renderHistory(){const body=$('historyBody');if(!s.rounds.length){body.innerHTML='<tr><td colspan="7" class="muted">No rounds yet</td></tr>';return}body.innerHTML='';[...s.rounds].reverse().forEach((r,idx)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${s.rounds.length-idx}</td><td>${r.p}</td><td>${r.b}</td><td>${money(r.pNet)}</td><td>${money(r.bNet)}</td><td>${money(r.total)}</td><td>${money(r.bankroll)}</td>`;body.appendChild(tr);})}
function renderAnalytics(){const box=$('nextShoeBox');if(!s.lastShoeSummary){box.textContent='No cleared shoe summary yet.';return}const x=s.lastShoeSummary;box.innerHTML=`Start: ${money(x.base)}<br>${x.type==='profit'?'Profit':'Loss'}: ${money(x.delta)}<br>Safety: ${money(x.safety)}<br><strong>Suggested: ${money(x.suggested)}</strong>`}
function renderLadder(){const wrap=$('ladderList');wrap.innerHTML='';let prev=0;s.ladder.forEach((bet,i)=>{const row=document.createElement('div');row.className='ladder-row';row.innerHTML=`<div>${i+1}</div><input value="${bet}" data-i="${i}"><div>${money(8*bet-prev)}</div>`;wrap.appendChild(row);prev+=bet;});const inputs=[...wrap.querySelectorAll('input')];inputs.forEach((inp,idx)=>{inp.onfocus=()=>inp.select();inp.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(inputs[idx+1]){inputs[idx+1].focus();inputs[idx+1].select();}}};inp.oninput=()=>{s.ladder[idx]=Number(inp.value||0);save();renderLadder();};});}
function render(){renderPlay();renderBoard();renderHistory();renderAnalytics();renderLadder()}
function bind(){['playerPad','bankerPad'].forEach(id=>{const wrap=$(id);for(let i=0;i<=9;i++){const b=document.createElement('button');b.className='key';b.textContent=i;b.onclick=()=>setPending(id==='playerPad'?'player':'banker',i);wrap.appendChild(b);}});document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelector(`.screen[data-screen="${t.dataset.tab}"]`).classList.add('active');});$('undoBtn').onclick=()=>{if(!s.rounds.length)return;const old=clone(s.rounds);old.pop();s.bankroll=s.settings.startingBankroll;s.rounds=[];s.pending={player:null,banker:null};s.player=side();s.banker=side();old.forEach(r=>commit(r.p,r.b));render();};$('clearBtn').onclick=()=>modal(MSG.clear,[{label:'Cancel'},{label:'OK',kind:' gold',onClick:()=>clearShoe(true)}]);$('newBtn').onclick=()=>clearShoe(false);$('csvBtn').onclick=()=>{const blob=new Blob([JSON.stringify(s.rounds,null,2)],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='history.csv';a.click();};$('pdfBtn').onclick=()=>{const blob=new Blob([JSON.stringify(s.rounds,null,2)],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='history.pdf';a.click();};$('autoBuildBtn').onclick=()=>{buildLadder();save();render();};$('saveSettingsBtn').onclick=()=>{s.settings.startingBankroll=Number($('startInput').value||30000);s.settings.targetAmount=Number($('targetInput').value||5000);s.settings.minBet=Number($('minInput').value||100);s.settings.maxBet=Number($('maxInput').value||3000);s.settings.multiple=Number($('multInput').value||100);s.settings.profitTarget=Number($('profitInput').value||500);s.settings.safetyReserve=Number($('safetyInput').value||20000);if(!s.rounds.length)s.bankroll=s.settings.startingBankroll;buildLadder();save();render();};}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));}
document.addEventListener('DOMContentLoaded',()=>{load();bind();render();});